project:
  type: website
  render:
    - index.qmd
    - "/DataViz/**/*.qmd"

website:
  title: "Catalogue des Viz proposé par le SSM Agriculture"
  site-url: "https://SSM-agriculture.github.io/site-DataViz/"
  navbar:
    left:
      - href: index.qmd
        text: Accueil
      - icon: github
        href: https://github.com/SSM-Agriculture/site-DataViz
    background: "#008000"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

filters:
   - include-code-files

